name: test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Start Docker Compose
              run: docker-compose up -d
            - name: Install Dependencies
              run: |
                  npm config set '//npm.pkg.github.com/:_authToken' "${TOKEN}"
                  npm install
              env:
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              run: npm run build && npm link
            - name: Apply DB Migrations
              env:
                  PGUSER: bongo
                  PGHOST: localhost
                  PGDATABASE: bongo_db
              run: bongojs migrate up
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test
